---
- name: Install packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - hostapd
  - dnsmasq

- name: Configure wlan0
  become: yes
  template:
    dest: /etc/systemd/network/wlan0.network
    src: wlan0.network.j2
  notify:
  - restart network

- name: Configure hostapd
  become: yes
  template:
    dest: /etc/hostapd/hostapd.conf
    src: hostapd.conf.j2
    mode: 600
  notify:
  - restart hostapd

- name: Start and enable hostapd
  become: yes
  service:
    name: hostapd
    state: started
    enabled: yes

- name: Configure dnsmasq
  become: yes
  template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
  notify:
  - restart dnsmasq

- name: Stop and disable systemd-resolved
  become: yes
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Configure /etc/resolv.conf
  become: yes
  template:
    dest: /etc/resolv.conf
    src: resolv.conf.j2

- name: Start and enable dnsmasq
  become: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes
